### ISSUE TITLE
Picopins Formatting on OSX

### ISSUE THREAD

**Issue by barrettfdavis** [RPiSpy/pi-pico#1]
Hi Matt, 

This is a great resource for getting up and running with picos. Hit a small snag getting the latest picopins script to display properly on my mac. As-is, it shows the formatting text alongside the intended display text without any colour.

Changing the ```\e``` formatting flags to ```\033``` seems to fix the issue. The latter flag I believe is cross-platform compatible and should make for an 'OK' drop in replacement. 

Cheers!

**Comment by RPiSpy** [comment]
Hello, sorry only just noticed this issue. So after a slight delay I've replaced instances of \e with \033. Seems to work the same on my Pi so hopefully it will improve the experience on OSX.
